//This code was autogenerated using micro-learn.
//Use the dummy variable array 'data' to interact with the ML inference.

double w[] = {-0.2946665411282507, 0.4669584958429627, -0.3759727859685976, 0.08311922594093986, 0.039605532870241815};

double c = -0.0016551194352874105;

void setup() {
    Serial.begin(9600);

}

void loop() {
    //Data Section: To Be Coded Manually

    float data[5]; //This is your feature vector. Retrive your data into this array.

    //ML Inference Section

    double temp = 0.0;
    for(int i=0; i<5; i++)
    {
        temp += (data[i] * w[i]);
    }

    if(temp >= c)
    {
        //Do something for class label Jeruk.
        Serial.println("Jeruk");
    }
    else
    {
        //Do something for class label Bukan Jeruk.
        Serial.println("Bukan Jeruk"); 
    }

    delay(1000);
}//This code was autogenerated using micro-learn.
//Use the dummy variable array 'data' to interact with the ML inference.

double w[] = {-1.214102786324796, 2.4580760871194065, -1.8544196538352034, 0.7948197488130005, -0.34325381699874946};

double c = 0.8051612224613983;

void setup() {
    Serial.begin(9600);

}

void loop() {
    //Data Section: To Be Coded Manually

    float data[5]; //This is your feature vector. Retrive your data into this array.

    //ML Inference Section

    double temp = 0.0;
    for(int i=0; i<5; i++)
    {
        temp += (data[i] * w[i]);
    }

    if(temp >= c)
    {
        //Do something for class label Jeruk.
        Serial.println("Jeruk");
    }
    else
    {
        //Do something for class label Bukan Jeruk.
        Serial.println("Bukan Jeruk"); 
    }

    delay(1000);
}//This code was autogenerated using micro-learn.
//Use the dummy variable array 'data' to interact with the ML inference.

double w[] = {-1.2692545158160775, 2.357697785802461, -1.9154983888033092, 0.7671320744999212, -0.22794994389299442};

double c = 0.6855553148939563;

void setup() {
    Serial.begin(9600);

}

void loop() {
    //Data Section: To Be Coded Manually

    float data[5]; //This is your feature vector. Retrive your data into this array.

    //ML Inference Section

    double temp = 0.0;
    for(int i=0; i<5; i++)
    {
        temp += (data[i] * w[i]);
    }

    if(temp >= c)
    {
        //Do something for class label Jeruk.
        Serial.println("Jeruk");
    }
    else
    {
        //Do something for class label Bukan Jeruk.
        Serial.println("Bukan Jeruk"); 
    }

    delay(1000);
}//This code was autogenerated using micro-learn.
//Use the dummy variable array 'data' to interact with the ML inference.

double w[] = {-1.24536788663413, 2.3178065429138854, -1.8822895200624084, 0.8287792354783255, -0.25778134656945634};

double c = 0.7395009636914766;

void setup() {
    Serial.begin(9600);

}

void loop() {
    //Data Section: To Be Coded Manually

    float data[5]; //This is your feature vector. Retrive your data into this array.

    //ML Inference Section

    double temp = 0.0;
    for(int i=0; i<5; i++)
    {
        temp += (data[i] * w[i]);
    }

    if(temp >= c)
    {
        //Do something for class label Jeruk.
        Serial.println("Jeruk");
    }
    else
    {
        //Do something for class label Bukan Jeruk.
        Serial.println("Bukan Jeruk"); 
    }

    delay(1000);
}//This code was autogenerated using micro-learn.
//Use the dummy variable array 'data' to interact with the ML inference.

double w[] = {-1.6984176056686755, 2.5052922403445756, -1.7443610919896262, 0.9800892626527746, 0.4955463658161529};

double c = 0.9402487879330321;

void setup() {
    Serial.begin(9600);

}

void loop() {
    //Data Section: To Be Coded Manually

    float data[5]; //This is your feature vector. Retrive your data into this array.

    //ML Inference Section

    double temp = 0.0;
    for(int i=0; i<5; i++)
    {
        temp += (data[i] * w[i]);
    }

    if(temp >= c)
    {
        //Do something for class label Jeruk.
        Serial.println("Jeruk");
    }
    else
    {
        //Do something for class label Bukan Jeruk.
        Serial.println("Bukan Jeruk"); 
    }

    delay(1000);
}//This code was autogenerated using micro-learn.
//Use the dummy variable array 'data' to interact with the ML inference.

double w[] = {-1.257234712344897, 2.5556704517926927, -1.8800414233623626, 0.7967607384328228, 0.427618015458614};

double c = 0.8970148990712401;

void setup() {
    Serial.begin(9600);

}

void loop() {
    //Data Section: To Be Coded Manually

    float data[5]; //This is your feature vector. Retrive your data into this array.

    //ML Inference Section

    double temp = 0.0;
    for(int i=0; i<5; i++)
    {
        temp += (data[i] * w[i]);
    }

    if(temp >= c)
    {
        //Do something for class label Jeruk.
        Serial.println("Jeruk");
    }
    else
    {
        //Do something for class label Bukan Jeruk.
        Serial.println("Bukan Jeruk"); 
    }

    delay(1000);
}//This code was autogenerated using micro-learn.
//Use the dummy variable array 'data' to interact with the ML inference.

double w[] = {-1.922742606821234, 2.5757386555063104, -1.9774926235849615, 0.9747700617439247, 0.6262169457396375};

double c = 0.8179083292172336;

void setup() {
    Serial.begin(9600);

}

void loop() {
    //Data Section: To Be Coded Manually

    float data[5]; //This is your feature vector. Retrive your data into this array.

    //ML Inference Section

    double temp = 0.0;
    for(int i=0; i<5; i++)
    {
        temp += (data[i] * w[i]);
    }

    if(temp >= c)
    {
        //Do something for class label Jeruk.
        Serial.println("Jeruk");
    }
    else
    {
        //Do something for class label Bukan Jeruk.
        Serial.println("Bukan Jeruk"); 
    }

    delay(1000);
}